name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: us-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      run: |
        # Login
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 132737078540.dkr.ecr.us-east-1.amazonaws.com
        # Build a docker container and push it to ECR 
        docker build . --file Dockerfile --tag test:latest
        echo "Tagging the image..."
        docker tag test:latest 132737078540.dkr.ecr.us-east-1.amazonaws.com/flask_jenkinsapp:latest
        echo "Pushing the image"
        docker push 132737078540.dkr.ecr.us-east-1.amazonaws.com/flask_jenkinsapp:latest
    
